Repository norcams/himlar, pull requests merged in 2018-12, with the labels that each got.

#535 Make sure all services uses keystone api v3
  hieradata/common/modules/ceilometer.yaml
  hieradata/common/modules/cinder.yaml
  hieradata/common/modules/designate.yaml
  hieradata/common/modules/glance.yaml
  hieradata/common/modules/gnocchi.yaml
  hieradata/common/modules/neutron.yaml
  hieradata/common/modules/nova.yaml
  hieradata/common/roles/volume.yaml
  profile/manifests/openstack/metric.pp
  profile/manifests/openstack/novactrl.pp
  profile/manifests/openstack/volume.pp
Labels: enhancement, review needed

#536 Automatically create network interfaces files on nodes
  hieradata/bgo/roles/compute.yaml
  hieradata/bgo/roles/storage.yaml
  hieradata/common/common.yaml
  hieradata/common/roles/builder.yaml
  hieradata/common/roles/logger.yaml
  hieradata/common/roles/monitor.yaml
  hieradata/common/roles/object.yaml
  hieradata/osl/roles/compute.yaml
  hieradata/osl/roles/storage.yaml
  hieradata/test01/roles/compute.yaml
  hieradata/test02/roles/compute.yaml
  profile/manifests/base/network.pp
  profile/templates/network/auto-if-bondslave.erb
  profile/templates/network/auto-if-teamslave.erb
  profile/templates/network/auto-if.erb
Labels: enhancement, new feature

#541 Extend firewall hack to work with multiple source and destiantions
  profile/manifests/firewall/expand_rule.pp
  profile/manifests/firewall/rule.pp
Labels: enhancement, need testing
