Repository norcams/himlar, pull requests merged in 2018-09, with the labels that each got.

#476 add dns node in test01 and test02
  hieradata/nodes/test01/test01-dns-01.yaml
  hieradata/nodes/test02/test02-dns-01.yaml
Labels: enhancement

#474 upgrade to queens for designate + revert to single node
  Puppetfile
  hieradata/common/common.yaml
  hieradata/common/modules/designate.yaml
  hieradata/common/roles/api.yaml
  hieradata/common/roles/dns.yaml
  hieradata/common/roles/ns.yaml
  hieradata/vagrant/roles/api.yaml
  nodes.yaml
  profile/manifests/openstack/designate.pp
Labels: enhancement

#479 Added memcached to keystone on identity
  hieradata/common/modules/keystone.yaml
  hieradata/common/roles/identity.yaml
Labels: enhancement, need testing

#477 Added cell management to novactrl
  hieradata/common/roles/novactrl.yaml
  profile/manifests/openstack/novactrl.pp
Labels: bugfix, need testing

#485 CephFS, mds, ec pools, ceph parameters etc
  hieradata/common/common.yaml
  hieradata/common/modules/ceph.yaml
  hieradata/common/roles/cephmds.yaml
  hieradata/common/roles/storage.yaml
  hieradata/local3/common.yaml
  hieradata/local3/roles/storage.yaml
  hieradata/nodes/local3/local3-cephmds-01.yaml
  hieradata/nodes/local3/local3-cephmds-02.yaml
  profile/manifests/storage/ceph_crushrules.pp
  profile/manifests/storage/ceph_ecpool.pp
  profile/manifests/storage/cephfs.pp
  profile/manifests/storage/cephmds.pp
  profile/manifests/storage/cephpool.pp
  profile/manifests/storage/cephpool_params.pp
Labels: enhancement, new feature

#488 set selinux enforcing on compute in prod
  hieradata/bgo/roles/compute.yaml
  hieradata/osl/roles/compute.yaml
Labels: security
