Repository norcams/himlar, pull requests merged in 2019-01, with the labels that each got.

#537 add stricter firewall config for ns and dns nodes
  hieradata/bgo/roles/dns.yaml
  hieradata/common/roles/dns.yaml
  hieradata/common/roles/ns.yaml
  hieradata/local1/roles/dns.yaml
  hieradata/local1/roles/ns.yaml
  hieradata/local2/roles/dns.yaml
  hieradata/local2/roles/ns.yaml
  hieradata/osl/roles/dns.yaml
  hieradata/test01/roles/dns.yaml
  profile/manifests/dns/ns.pp
  profile/manifests/openstack/designate.pp
Labels: need testing, security

#549 add class to reload systemd, add systemd unit template
  profile/manifests/base/systemd.pp
  profile/templates/base/systemd-unit.erb
Labels: new feature

#550 add code in dashboard.pp to create systemd extras for httpd
  profile/manifests/openstack/dashboard.pp
Labels: enhancement

#552 Add new network variables
  hieradata/bgo/common.yaml
  hieradata/common/common.yaml
  hieradata/local1/common.yaml
  hieradata/local2/common.yaml
  hieradata/local3/common.yaml
  hieradata/osl/common.yaml
  hieradata/test01/common.yaml
  hieradata/test02/common.yaml
  hieradata/tos/common.yaml
  hieradata/vagrant/common.yaml
Labels: review needed

#533 add designate nodes in osl and bgo
  hieradata/nodes/bgo/bgo-dns-01.yaml
  hieradata/nodes/bgo/bgo-torack-01.yaml
  hieradata/nodes/bgo/bgo-torack-02.yaml
  hieradata/nodes/osl/osl-dns-01.yaml
  hieradata/nodes/osl/osl-torack-01.yaml
  hieradata/nodes/osl/osl-torack-02.yaml
Labels: review needed
