Repository norcams/himlar, pull requests merged in 2019-02, with the labels that each got.

#540 Added new coordinator role with zookeeper
  Puppetfile
  hieradata/common/modules/zookeeper.yaml
  hieradata/common/roles/coordinator.yaml
  hieradata/nodes/vagrant/vagrant-coordinator-01.yaml
  profile/manifests/highavailability/zookeeper.pp
Labels: enhancement, new feature

#572 Reworked systemd limits
  hieradata/common/roles/dashboard.yaml
  hieradata/common/roles/db.yaml
  profile/manifests/base/systemd.pp
  profile/manifests/base/systemd/limits.pp
  profile/manifests/openstack/dashboard.pp
Labels: enhancement

#569 multiple image nodes
  hieradata/bgo/roles/api.yaml
  hieradata/common/common.yaml
  hieradata/nodes/bgo/bgo-image-02.yaml
  hieradata/nodes/bgo/bgo-image-03.yaml
  hieradata/nodes/osl/osl-image-02.yaml
  hieradata/nodes/osl/osl-image-03.yaml
  hieradata/nodes/test01/test01-image-02.yaml
  hieradata/nodes/test02/test02-image-02.yaml
  hieradata/nodes/vagrant/vagrant-image-02.yaml
  hieradata/osl/roles/api.yaml
  hieradata/test01/roles/api.yaml
  hieradata/test02/roles/api.yaml
  hieradata/vagrant/roles/api.yaml
Labels: review needed

#573 Object ceph
  Rakefile
  hieradata/common/common.yaml
  hieradata/common/modules/ceph.yaml
  hieradata/common/roles/admin.yaml
  hieradata/common/roles/api.yaml
  hieradata/common/roles/cephmon-object.yaml
  hieradata/common/roles/object-ceph.yaml
  hieradata/common/roles/object-swift.yaml
  hieradata/common/roles/rgw.yaml
  hieradata/local1/common.yaml
  hieradata/local1/modules/profile.yaml
  hieradata/local1/roles/api.yaml
  hieradata/local1/roles/object-ceph.yaml
  hieradata/local1/roles/object-swift.yaml
  hieradata/local1/roles/rgw.yaml
  hieradata/nodes/local1/local1-cephmon-object-01.yaml
  hieradata/nodes/local1/local1-object-ceph-01.yaml
  hieradata/nodes/local1/local1-object-ceph-02.yaml
  hieradata/nodes/local1/local1-object-ceph-03.yaml
  hieradata/nodes/local1/local1-rgw-01.yaml
  hieradata/nodes/vagrant/vagrant-cephmon-object-01.yaml
  hieradata/nodes/vagrant/vagrant-object-ceph-01.yaml
  hieradata/nodes/vagrant/vagrant-object-ceph-02.yaml
  hieradata/nodes/vagrant/vagrant-object-ceph-03.yaml
  hieradata/nodes/vagrant/vagrant-object-swift-01.yaml
  hieradata/nodes/vagrant/vagrant-object-swift-02.yaml
  hieradata/nodes/vagrant/vagrant-object-swift-03.yaml
  hieradata/nodes/vagrant/vagrant-rgw-01.yaml
  hieradata/vagrant/common.yaml
  hieradata/vagrant/modules/profile.yaml
  hieradata/vagrant/roles/api.yaml
  hieradata/vagrant/roles/object-ceph.yaml
  hieradata/vagrant/roles/object-swift.yaml
  nodes.yaml
  profile/files/openstack/horizon/overrides.py
  profile/manifests/openstack/identity.pp
  profile/manifests/openstack/object/loopback.pp
  profile/manifests/openstack/object/radosgw.pp
  profile/manifests/storage/ceph/config.pp
  profile/manifests/storage/ceph/pool.pp
  profile/manifests/storage/ceph/pool/config.pp
  profile/manifests/storage/ceph/pool/ec.pp
  profile/manifests/storage/ceph/pool/tier.pp
  profile/manifests/storage/loopback.pp
  provision/patches/object-ceph/loopback.diff
  provision/patches/script/object-ceph.sh
Labels: new feature
